# Generated by Django 4.0.2 on 2022-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_genre_genre_description'),
        ('users', '0003_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keyword',
            field=models.ManyToManyField(blank=True, to='catalog.Keyword'),
        ),
    ]
