# Generated by Django 4.0.2 on 2022-02-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_film_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='castandcrew',
            name='man',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.people'),
        ),
        migrations.AlterField(
            model_name='people',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='deathday',
            field=models.DateField(null=True),
        ),
    ]
