# Generated by Django 4.0.2 on 2022-02-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_castandcrew_man_alter_people_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
