# Generated by Django 4.0.2 on 2022-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
