# Generated by Django 4.0.2 on 2022-02-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_people_birthday_alter_people_deathday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
