# Generated by Django 4.0.2 on 2022-02-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_people_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
