# Generated by Django 4.0.2 on 2022-02-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_review_user_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('positive', 'Положительная'), ('negative', 'Отрицательная')], max_length=200),
        ),
    ]
