# Generated by Django 4.0.2 on 2022-02-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_rating',
            field=models.FloatField(null=True),
        ),
    ]
