# Generated by Django 4.0.2 on 2022-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_film_film_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-film_rating']},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='film',
            name='film_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
